export const categories = {
  man: [
    'New arrivals',
    'Shirts',
    'Coats',
    'Jakets',
    'Sweaters',
    'Polos & Tees',
    'J',
    'Outerwear',
  ],
  woman: [
    'New arrivals',
    'Dresses',
    'Knitwear',
    'Coats',
    'Jackets',
    'Suits & Combined',
    'T-shirts',
    'Jeans',
    'Skirts',
    'Underwear',
  ],
  accessories: [
    'Bags',
    'Wallets',
    'Belts',
    'Scarves & hats',
    'Sunglasses',
    'Bags',
    'Waletts, Card Cases',
    'Belts',
    'Ties & Cummerbunds',
    'Sunglasses',
  ],
}
